name: Test, Bump Version, and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: |
          pytest

  bump-and-build:
    name: Bump version and build package
    permissions:
      contents: write
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\r' | sed ':a;N;$!ba;s/\n/ /g')
          echo "Commit message: $COMMIT_MSG"
          echo "msg=$COMMIT_MSG" >> "$GITHUB_OUTPUT"

      - name: Skip if 'no bump' is in commit message
        if: contains(steps.get_commit.outputs.msg, 'no bump')
        run: |
          echo "Skipping version bump due to 'no bump' in commit message."
          exit 0

      - name: Set up Python
        if: ${{ !contains(steps.get_commit.outputs.msg, 'no bump') }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install bump-my-version and build tools
        if: ${{ !contains(steps.get_commit.outputs.msg, 'no bump') }}
        run: |
          python -m pip install --upgrade pip
          pip install bump-my-version build

      - name: Bump patch version
        if: ${{ !contains(steps.get_commit.outputs.msg, 'no bump') }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          bump-my-version bump patch

      - name: Push changes and tag
        if: ${{ !contains(steps.get_commit.outputs.msg, 'no bump') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main
          git push origin v$(bump-my-version show current_version)

      - name: Build package
        if: ${{ !contains(steps.get_commit.outputs.msg, 'no bump') }}
        run: python -m build

      - name: Upload artifacts to release
        if: ${{ !contains(steps.get_commit.outputs.msg, 'no bump') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name=v$(bump-my-version show current_version)
          gh release create "$tag_name" dist/* --title "$tag_name" --notes "Automated release for $tag_name" || \
          gh release upload "$tag_name" dist/*
